apiVersion: v1
kind: Service
metadata:
  labels:
    app: l2c-frontend
  name: l2c-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: l2c-frontend
  type: LoadBalancer
