apiVersion: v1
kind: Service
metadata:
  labels:
    app: l2c-frontend
    argocd.argoproj.io/instance: l2c
  name: l2c-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: l2c-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
